from PIL import Image
from numpy import asarray
import os

# file names
image_name = "map3.png"
map_name = "map2.map"

# map parameters (no SPACEs)
bg_name = "MountainDusk"
music_name = "Nightmare.wav"


# load the image
image = Image.open(image_name)
# convert image to numpy array
data = asarray(image)

(width, height, alpha) = data.shape

f = open(map_name, "w")
f.write("|MAP GENERATED BY createmap.py\n")
f.write("BACKGROUND " + bg_name + "\n")
f.write("MUSIC " + music_name + "\n")
f.write("SIZE " + str(height) + " " + str(width) + "\n")
f.write("GRAVITY 512\n")
f.write("DEFAULT_FRICTION 0.8 0\n")


'''
tile ids are [0...420]
encoding used for tiles:
RGB value       id
[0 0 0]     - >  0
[0 0 1]     - >  1
...
[4 2 0]     - >  420

entities:
[255 255 255]   - > player
[255 255 1]     - > enemy
'''


for i in range(width):
    for j in range(height):
        pixel = data[i][j]

        if pixel[0]==255 and pixel[1]==255 and pixel[2]==255:
            f.write("PLAYER ")
            f.write(str(j*32))
            f.write(" ")
            f.write(str(i*32))
            f.write("\n")
            continue

        if pixel[0]==255 and pixel[1]==255 and pixel[2]==1:
            f.write("ENEMY Rat ")
            f.write(str(j*32))
            f.write(" ")
            f.write(str(i*32))
            f.write("\n")
            continue

        if pixel[0]==255 and pixel[1]==255 and pixel[2]==2:
            f.write("ENEMY Skeleton ")
            f.write(str(j*32))
            f.write(" ")
            f.write(str(i*32))
            f.write("\n")
            continue

        if pixel[0]==0 and pixel[1]==0 and pixel[2]==0 and pixel[3]==0:
            continue


        r = pixel[0]
        g = pixel[1]
        b = pixel[2]

        value = r*100 + g*10 + b

        if(value >= 0 and value <= 420):
            f.write("TILE ")
            f.write(str(value))
            f.write(" ")
            f.write(str(j))
            f.write(" ")
            f.write(str(i))
            f.write("\n")
            

f.close()

command = 'mv ' + map_name + ' ../../Resources/media/Maps'

os.system(command)