import csv
import os

# file names
map_name = "map2.map.background"

isBackground = True

# map parameters (no SPACEs)
bg_name = "MountainDusk"
music_name = "Nightmare.wav"


f = open(map_name, "w")
f.write("|MAP GENERATED BY createmap.py\n")

if(not isBackground):
    f.write("BACKGROUND " + bg_name + "\n")
    f.write("MUSIC " + music_name + "\n")
    f.write("SIZE " + str(40) + " " + str(40) + "\n")
    f.write("GRAVITY 512\n")
    f.write("DEFAULT_FRICTION 0.8 0\n")


csvfile = open('layer22.csv')

csvreader = csv.reader(csvfile)

for i,row in enumerate(csvreader):
    for j,tile in enumerate(row):
        #print(tile,type(tile),j)
        if(tile=='-1'):
            continue
        else:
            if(tile=='1763'):
                f.write("PLAYER ")
                f.write(str(j*32))
                f.write(" ")
                f.write(str(i*32))
                f.write("\n")
            else:
                f.write("TILE ")
                f.write(tile)
                f.write(" ")
                f.write(str(j))
                f.write(" ")
                f.write(str(i))
                f.write("\n")
            

csvfile.close()
f.close()

command = 'mv ' + map_name + ' ../../Resources/media/Maps'

os.system(command)